### PR TITLE
Fix MSVC compilation issues

### LINKED ISSUE #15: 2.0132 does not build with Visual Studio 2010, 2.0123 does
Hi,
the problem is that perl-libxml-sax.c cannot be compiled. It seems that the very basic perl things are unknown in this file. E.g. in line 854 there's the dTHX macro.
2.0123 builds okay in the very same context. Also 2.0132 builds on Unixes and Linux. Only Windows and 2.0132 is a problem. Here's the beginning of the error:

`        cl -c  -IC:\SAPDevelop\hmexternals\perl\gen\out\build-64de87d5\libxml_helpdir\include  -nologo -GF -W3 -O1 -MD -Zi -DNDEBUG -GL -fp:precise -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIV
E -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -O1 -MD -Zi -DNDEBUG -GL -fp:precise    -DVERSION=\"2.0132\"  -DXS_VERSION=
\"2.0132\"  "-IC:\SAPDevelop\hmexternals\perl\gen\out\perl-5.24.1-sap16-SNAPSHOT-ntamd64-release-c\lib\CORE"  -DHAVE_UTF8 perl-libxml-sax.c
perl-libxml-sax.c
perl-libxml-sax.c(326) : warning C4244: '=' : conversion from 'IV' to 'int', possible loss of data
perl-libxml-sax.c(854) : error C2275: 'PerlInterpreter' : illegal use of this type as an expression
        C:\SAPDevelop\hmexternals\perl\gen\out\perl-5.24.1-sap16-SNAPSHOT-ntamd64-release-c\lib\CORE\perl.h(2631) : see declaration of 'PerlInterpreter'
perl-libxml-sax.c(854) : error C2065: 'my_perl' : undeclared identifier
perl-libxml-sax.c(857) : error C2065: 'my_perl' : undeclared identifier
...
Stop.
`

Do you have an idea, what's wrong here?

T&R
Marc-Philip

### PR DESCRIPTION
**Pull request by rurban**
Closes #15.
Repro this by disabling PERL_NO_GET_CONTEXT in perl-libxml-sax.c
and use a threaded perl.
Several perl helper functions miss the my_perl argument, resp. a global dTHX;
i.e. PL_sv_undef needs dTHX

### CODE REVIEW

**Comment by shlomif** [comment]
Merged, thanks!
